version: 3.1;
services:
  nginx:
    depends_on:
      - api
      - client
    image: "doriangrey1911/checkpoint-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - 80:80

  api:
    image: "doriangrey1911/checkpoint-api"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "doriangrey1911/checkpoint-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    image: "doriangrey1911/checkpoint-client"
    mem_limit: 128m
    hostname: client

    