name: Docker CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12  # Use a Docker version that meets your needs
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker images for deployment
        run: |
          docker build -t ${{ secrets.DOCKER_ID }}/checkpoint-client ./client
          docker build -t ${{ secrets.DOCKER_ID }}/checkpoint-api ./server
          docker build -t ${{ secrets.DOCKER_ID }}/checkpoint-worker ./worker
          docker build -t ${{ secrets.DOCKER_ID }}/checkpoint-nginx ./nginx

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_ID }}/checkpoint-client
          docker push ${{ secrets.DOCKER_ID }}/checkpoint-api
          docker push ${{ secrets.DOCKER_ID }}/checkpoint-worker
          docker push ${{ secrets.DOCKER_ID }}/checkpoint-nginx

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Deploy to Elastic Beanstalk
        run: |
          pip install awsebcli
          eb init -p docker Checkpoint-docker-prod-1 --region eu-central-1
          eb use Checkpoint-docker-prod-1
          eb deploy
